### ISSUE TITLE
Error: config.reporters must be an array of strings or functions

### ISSUE THREAD

**Issue by qburst-hari** [webdriverio-community/wdio-html-reporter#1]
my webdriverio with cucumber and mocha I am getting this error. 

```
project/node_modules/webdriverio/build/lib/launcher.js:209
                reporter.add(new Reporter(reporter, config, reporterOptions));

TypeError: Reporter is not a constructor
```

Could you please check @rpii

**Comment by rpii** [comment]
It works fine with this syntax:

    reporters: [
        'spec',
        // ['allure', {
        //     outputDir: '/reports/allure-reports/',
        //     disableWebdriverStepsReporting: true,
        //     disableWebdriverScreenshotsReporting: false
        // }],
        // ['junit', {
        //     outputDir: './reports/junit-reports/',
        //     outputFileFormat: function(opts) { // optional
        //         return `results-${opts.cid}.${opts.capabilities}.xml`
        //     }
        // }
        // ],
        ['@rpii/wdio-html-reporter', {
            debug: false,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'Test Report',
            showInBrowser:true,
            useOnAfterCommandForScreenshot:false
        }
        ],


    ],

Which is an array.  You must not have an array.
