### ISSUE TITLE
Is commonjs still supported

### ISSUE THREAD

**Issue by vBitza** [webdriverio-community/wdio-html-reporter#101]
Hi, does this package still support CommonJS or in order to use it the Wdio Project must by migrated to Modules?

**Comment by rpii** [comment]
webdriverio 8 is modules,  look at the samples they provide.  so yes it is

**Comment by vBitza** [comment]
Hi, yes I understand it supports module based on the given sample, my question was if the CommonJS is still supported. 

Basically In their sample they are using Import instead of Require:

import {ReportGenerator, HtmlReporter} from 'wdio-html-nice-reporter';



I tried setting it up with require and it didn't work, so I thought I would ask for an official answer or maybe someone managed to set it up in some way.

**Comment by rpii** [comment]
I believe you should ask the webdriverio team for an official answer.   In
my experience require will not work with modules.

**Comment by rpii** [comment]
Here are is my tsconfig file.  the package type is set to module

**Comment by gpaciga** [comment]
See #104; WDIO v8 was written so that it would be compatible with existing CJS suites, and it would be nice if this module could follow that same pattern.

**Comment by vBitza** [comment]
Closing this issue as resolved.

Bottom line is as of 18.8.2023, the latest version of wdio-html-reporter 7.7.1 does not support CJS, it works with Modules only. 

Follow up will be done once the project starts getting maintained by the Wdio community as per #104 

Thanks all!
