### ISSUE TITLE
Rename the default branch from master to main

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio-community/wdio-html-reporter#109]
This change would align with the other repos in webdriverio and webdriverio-community.

For more see https://github.com/github/renaming?tab=readme-ov-file#renaming-the-default-branch-from-master.

**Comment by seanpoulter** [comment]
Could you please help @christian-bromann? I don't have permissions to rename the branch or merge Dependabot PRs like https://github.com/webdriverio-community/wdio-html-reporter/pull/97.

**Comment by christian-bromann** [comment]
Done. Thanks for pointing this out.
