### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by goldengecko** [webdriverio-community/wdio-html-reporter#17]
Firstly, thanks for your work on making this available.

In the documentation it says `See the report.test.js for configuration` but there doesn't appear to be any file by that name. I believe it should be referring to `reporter.spec.js`

In the section `To take a screenshot after test assert:` it indicates you should both use `browser.saveScreenshot(filepath);` and `process.emit('test:screenshot', filepath);` but in the default settings where `useOnAfterCommandForScreenshot` is turned on, it already processes the screenshot and pushes the screenshot event. Having both commands results in the inclusion of two screenshots in the report.

Perhaps it would save others some time if these things were corrected.

**Comment by rpii** [comment]
I updated the documentation, but I really dont have much time for that.  Feel free to make any improvements.
