### ISSUE TITLE
Asterisk in Describe causes silent failure of full report generation

### ISSUE THREAD

**Issue by alexander-warner** [webdriverio-community/wdio-html-reporter#19]
Depending on test execution order, sometimes the Describe with an asterisk will cause the whole report to fail to generate.

```
describe('test2 * yep', function () {
    fit('test fit', () => {
        console.log("made it2");
    });
});
```

Please let me know if there was a way to see an error message. (It took like 40 hours to chop our tests down to finally find the cause.)

**Comment by rpii** [comment]
I'll take a look at it. I am assuming the * is only affecting the
wdio-html-reporter?

thanks
Rich

**Comment by alexander-warner** [comment]
Oh, like, is webdriverio and the tests running? Yep. Thanks!

**Comment by rpii** [comment]
I didnt have any success replicating this.  Is it only happening  in the mocha ui mode TDD?
Any chance you could create a small test that replicates it?

**Comment by alexander-warner** [comment]
Interesting, the code clip I put above was the entire spec.js file that I ended up using to reproduce it before posting here. I'll try creating a new project and limiting which npm packages are installed. Some general notes:
-we are using jasmine
-this is a package.json i last tested the above spec file with:
```
{
  "name": "webdriverio-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/preset-env": "^7.8.4",
    "@rpii/wdio-html-reporter": "^0.8.6",
    "@types/jest": "^24.0.23",
    "@wdio/cli": "^5.13.2",
    "@wdio/dot-reporter": "^5.13.2",
    "@wdio/jasmine-framework": "^5.16.15",
    "@wdio/local-runner": "^5.16.15",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.16.15",
    "axe-core": "^3.4.0",
    "chromedriver": "^77.0.0",
    "jest": "^24.9.0",
    "jest-html-reporters": "^1.2.1",
    "wdio-chromedriver-service": "^5.0.2",
    "date-and-time": "^0.12.0"
  },
  "dependencies": {
    "jquery": "^3.4.1",
    "log4js": "^6.1.1"
  }
}
```

**Comment by alexander-warner** [comment]
Here is a minimal wdio.config.js file - let me know if i should make it more minimal somehow:
```
const { HtmlReporter } = require("@rpii/wdio-html-reporter");
const log4js = require("log4js");
exports.config = {
  runner: "local",
  specs: [
    "./tests/user-administration-specs/**/*.js"
  ],
  exclude: [],
  maxInstances: 1,
  capabilities: [
    {
      browserName: "chrome",
      "goog:chromeOptions": {
      }
    }
  ],
  logLevel: "info",
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ["selenium-standalone"],
  framework: "jasmine",
  reporters: [
    "spec",
    [
      HtmlReporter,
      {
        debug: true,
        showInBrowser: false,
        useOnAfterCommandForScreenshot: false,
        LOG: log4js.getLogger("default")
      }
    ]
  ],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 90000,
  },
  beforeSuite: function(suite) {
  },
};
```

**Comment by rpii** [comment]
thanks that should be enough to get the ball rolling
Rich

**Comment by rpii** [comment]
So I was looking at this and I cant make replicate the issue...  Any other ideas?

**Comment by alexander-warner** [comment]
Did you check that it actually created a report? I still see empty directories created - even on the 1.0.3

**Comment by alexander-warner** [comment]
windows os btw

**Comment by rpii** [comment]
needed to encode suiteUid and cid to avoid invalid file names
