### ISSUE TITLE
no report is generated for cucumber tests

### ISSUE THREAD

**Issue by pako88** [webdriverio-community/wdio-html-reporter#20]
with mocha framework everythings fine, but no report is generated for cucumber tests.
i got following error message:
```
[0-0] PASSED in chrome - D:\Repos\webdriverio-common\test\features\smoke.feature
(node:18488) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'info' of undefined
    at ReportAggregator.createReport (D:\Repos\webdriverio-common\node_modules\@rpii\wdio-html-reporter\src\reportAggregator.js:117:39)
    at D:\Repos\webdriverio-common\config\shared.conf.ts:422:40
    at Object.onComplete (D:\Repos\webdriverio-common\config\shared.conf.ts:427:7)
    at D:\Repos\webdriverio-common\node_modules\@wdio\cli\build\utils.js:82:13
    at Array.map (<anonymous>)
    at runOnCompleteHook (D:\Repos\webdriverio-common\node_modules\@wdio\cli\build\utils.js:80:37)
    at Launcher.run (D:\Repos\webdriverio-common\node_modules\@wdio\cli\build\launcher.js:78:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
does anyone got this reporter running with cucumber?

**Comment by rpii** [comment]
typically that error indicates the the report structure did not get built
correctly by the proper report events being fired and saving off the data.
I havent used it with cucumber.

**Comment by rpii** [comment]
Ive published a new version that will output some diagnostics in this
case.  I will need a test case or you can see if the diagnostics shed any
light on the issue

Rich

**Comment by pako88** [comment]
with the new version (0.8.8), the tests didn't even start (also in mocha this time)

```
2020-03-16T06:10:45.596Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: D:\Repos\webdriverio-common\config\local.conf.js: Cannot find module './reporter'
```

i'll try to set up an example project

**Comment by pako88** [comment]
i found the error for version 0.8.6.
if there are quotes (") in the scenario description, the result files aren't generated from the reporter...

**Comment by rpii** [comment]
Could you send me an example and I will look into it?

thanks
Rich

**Comment by pako88** [comment]
https://github.com/pako88/WebdriverIO_v5_TypeScript/blob/html-reporter-with-quotes/package.json#L8

Just run the "test-cucumber" npm script in the branch "html-reporter-with-quotes"

**Comment by rpii** [comment]
Thanks for the great example.  I was able to sort out the issues with cucumber and its working now.  Go ahead and try version 1.0.0 and let me know how it works for you.  I did make a couple of changes to your sample project.
