### ISSUE TITLE
TypeError: Cannot read property 'createReport' of undefined (while generating master report)

### ISSUE THREAD

**Issue by drptbl** [webdriverio-community/wdio-html-reporter#26]
```
 (node:78) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createReport' of undefined
     at /home/node/app/node_modules/xxx/e2e-fwk/conf/e2e.base.conf.js:361:37
     at Object.onComplete (/home/node/app/node_modules/xxx/e2e-fwk/conf/e2e.base.conf.js:370:7)
     at Promise.all.onCompleteHook.map (/home/node/app/node_modules/@wdio/cli/build/utils.js:82:13)
     at Array.map (<anonymous>)
     at runOnCompleteHook (/home/node/app/node_modules/@wdio/cli/build/utils.js:80:37)
     at Launcher.run (/home/node/app/node_modules/@wdio/cli/build/launcher.js:83:69)
     at process._tickCallback (internal/process/next_tick.js:68:7)
 (node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 error Command failed with exit code 1.
```

^ Getting following error after doing step-by-step setup for master report from README.
Using wdio@6 & node 10.

**Comment by drptbl** [comment]
These changes fixed it for me:
```
  onPrepare: (config, capabilities) => {
    // eslint-disable-next-line prefer-const
    global.reportAggregator = new ReportAggregator({
      outputDir: `${reportsPath}/html-report/`,
      filename: 'master-report.html',
      reportTitle: `Master Report for ${process.env.REVIEW_URL}`,
      browserName: browser.capabilities.browserName
    }).clean();
  },
```

```
  onComplete: (exitCode, config, capabilities, results) => {
    global.reportAggregator.createReport({
      config: config,
      capabilities: capabilities,
      results: results
    });
  },
```

Cheers.

**Comment by rpii** [comment]
createReport doesnt require any parameters anymore.  look the the
typescript bindings

Rich

**Comment by drptbl** [comment]
My main point was that if someone follow the README, there is no way to make it work. It's outdated.

Same here:
https://webdriver.io/docs/rpii-wdio-html-reporter.html

**Comment by rpii** [comment]
I thought I had updated that.  Sorry about that... its updated now in git
and I will publish it soon.

**Comment by rpii** [comment]
I created an issue for the cucumber test.  Is not working

**Comment by argirovatina** [comment]
I am still facing this issue.
````
const {ReportAggregator, HtmlReporter} = require("@rpii/wdio-html-reporter");

exports.config = {
  // debug: true,
  baseUrl: 'test.com',
  specs: [
    "./e2e/tests/**/**-spec.ts"
  ],
  runner: 'local',
  port: 9515,
  path: '/',
  services: [
    ['chromedriver', {
      args: ['--silent'] //
    }]
  ],
  capabilities: [{
    maxInstances: 1,
    browserName: 'chrome',
    'goog:chromeOptions': {
      args: ["--headless, --disable-gpu", "no-sandbox", "incognito", "--window-size=1920,1500"]
    }
  }],
  outputDir: "./e2e/logs",
  waitForTimeout: 1000,
  coloredLogs: true,
  screenshotOnReject: {
    connectionRetryTimeout: 30000,
    connectionRetryCount: 0
  },
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    helpers: [require.resolve('@babel/register')]
  },
  reporters: [
    'spec',
    ['allure', {
      outputDir: './e2e/test-reports/allure-results',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: true,
    }]
  ],
  reporterOptions: {
    allure: {
      outputDir: './e2e/test-reports/allure-results'
    }
      [HtmlReporter, {
      outputDir: './e2e/test-reports/',
      filename: 'report.html',
      reportTitle: 'Test Report Title',
      showInBrowser: true,
      useOnAfterCommandForScreenshot: false,
    }
      ]
  },
  beforeSession: function (config, capabilities, specs) {
    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.e2e.json')
    })
  },

  onPrepare: function (config, capabilities) {
    let reportAggregator = new ReportAggregator({
      outputDir: './e2e/test-reports/',
      filename: 'master-report.html',
      reportTitle: 'Master Report',
      browserName: browser.capabilities.browserName,
template.hbs')
    });
    reportAggregator.clean();
    global.reportAggregator = reportAggregator;
  },

  afterTest: function (test) {
    const path = require('path');
    const moment = require('moment');

    if (test.passed) {
      return;
    }
    const timestamp = moment().format('YYYYMMDD-HHmmss.SSS');
    const filepath = path.join('./e2e/test-reports/screenshots/', timestamp + '.png');
    browser.saveScreenshot(filepath);
    process.emit('test:screenshot', filepath);
    browser.reloadSession();
  },

  onComplete: function (exitCode, config, capabilities, results) {
    (async () => {
      await global.reportAggregator.createReport();
    })();
  }
}
```
`

**Comment by chandrasekhar11** [comment]
> I am still facing this issue.
> 
> ```
> const {ReportAggregator, HtmlReporter} = require("@rpii/wdio-html-reporter");
> 
> exports.config = {
>   // debug: true,
>   baseUrl: 'test.com',
>   specs: [
>     "./e2e/tests/**/**-spec.ts"
>   ],
>   runner: 'local',
>   port: 9515,
>   path: '/',
>   services: [
>     ['chromedriver', {
>       args: ['--silent'] //
>     }]
>   ],
>   capabilities: [{
>     maxInstances: 1,
>     browserName: 'chrome',
>     'goog:chromeOptions': {
>       args: ["--headless, --disable-gpu", "no-sandbox", "incognito", "--window-size=1920,1500"]
>     }
>   }],
>   outputDir: "./e2e/logs",
>   waitForTimeout: 1000,
>   coloredLogs: true,
>   screenshotOnReject: {
>     connectionRetryTimeout: 30000,
>     connectionRetryCount: 0
>   },
>   framework: 'jasmine',
>   jasmineNodeOpts: {
>     showColors: true,
>     defaultTimeoutInterval: 30000,
>     helpers: [require.resolve('@babel/register')]
>   },
>   reporters: [
>     'spec',
>     ['allure', {
>       outputDir: './e2e/test-reports/allure-results',
>       disableWebdriverStepsReporting: true,
>       disableWebdriverScreenshotsReporting: true,
>     }]
>   ],
>   reporterOptions: {
>     allure: {
>       outputDir: './e2e/test-reports/allure-results'
>     }
>       [HtmlReporter, {
>       outputDir: './e2e/test-reports/',
>       filename: 'report.html',
>       reportTitle: 'Test Report Title',
>       showInBrowser: true,
>       useOnAfterCommandForScreenshot: false,
>     }
>       ]
>   },
>   beforeSession: function (config, capabilities, specs) {
>     require('ts-node').register({
>       project: require('path').join(__dirname, './tsconfig.e2e.json')
>     })
>   },
> 
>   onPrepare: function (config, capabilities) {
>     let reportAggregator = new ReportAggregator({
>       outputDir: './e2e/test-reports/',
>       filename: 'master-report.html',
>       reportTitle: 'Master Report',
>       browserName: browser.capabilities.browserName,
> template.hbs')
>     });
>     reportAggregator.clean();
>     global.reportAggregator = reportAggregator;
>   },
> 
>   afterTest: function (test) {
>     const path = require('path');
>     const moment = require('moment');
> 
>     if (test.passed) {
>       return;
>     }
>     const timestamp = moment().format('YYYYMMDD-HHmmss.SSS');
>     const filepath = path.join('./e2e/test-reports/screenshots/', timestamp + '.png');
>     browser.saveScreenshot(filepath);
>     process.emit('test:screenshot', filepath);
>     browser.reloadSession();
>   },
> 
>   onComplete: function (exitCode, config, capabilities, results) {
>     (async () => {
>       await global.reportAggregator.createReport();
>     })();
>   }
> }
> ```
> `
> ``` 

Is this resolved ? whats the solution ?

**Comment by juliogomezv** [comment]
Does someone solve this error?

**Comment by rpii** [comment]
The solution is what I have stated.  You need the code in the onPrepare
function...  set a breakpoint there and make sure the global object is
created...

  onPrepare: function (config, capabilities) {
    let reportAggregator = new ReportAggregator({
      outputDir: './e2e/test-reports/',
      filename: 'master-report.html',
      reportTitle: 'Master Report',
      browserName: browser.capabilities.browserName,
template.hbs')
    });
    reportAggregator.clean();
    global.reportAggregator = reportAggregator;
  },
