### ISSUE TITLE
Browser name instead of cid

### ISSUE THREAD

**Issue by senovsky** [webdriverio-community/wdio-html-reporter#3]
Hi, would it be possible to add an option to show browser name in the first `<h3>` instead of `info.cid`? It would improve the clarity of the report and make an awesome reporter even better! :-)

**Comment by rpii** [comment]
That shouldn’t be too tough… I will look at it

**Comment by rpii** [comment]
So I added the browser and webdriver parameters to the top of the report... go ahead and check it out

**Comment by senovsky** [comment]
Now that I've got the reporter working again, I can confirm that the browser name is displayed indeed :-)
