### ISSUE TITLE
Can't turn off verbose logger for tests

### ISSUE THREAD

**Issue by astunkojis** [webdriverio-community/wdio-html-reporter#32]
I have set debug to false, and there is no  LOG: log4j.getLogger("default") in the settings. My settings for reporter:
```
[HtmlReporter, {
      debug: false,
      filename: `report-${moment().format('YYYY-MM-DD-HH[h]mm[min]')}.html`,
      reportTitle: 'automation',
      //to show the report in a browser when done
      showInBrowser: false,
      //to turn on screenshots after every test
      useOnAfterCommandForScreenshot: false,
    }
    ]
```
and still I get a ton on unneeded info in the terminal while test run, how to turn that off?

**Comment by rpii** [comment]
I have created a new version which exports the log4js-api correctly so you can stub it out.  Please try it and let me know if it works correctly for you.

**Comment by astunkojis** [comment]
Thank you, that helped:)
