### ISSUE TITLE
Detailed overview report

### ISSUE THREAD

**Issue by sisirrana** [webdriverio-community/wdio-html-reporter#35]
I am able to use the reporter to generate the HTML report for my tests. I am looking for a detailed overview report which gives a kind of summary Features, Scenarios and Steps wise. I am trying to customize the template. But i am only able to get methods to for tests/steps.
 <td>{{metrics.passed}}</td>
 <td>{{metrics.skipped}}</td>
 <td>{{metrics.failed}}</td>
Do we have similar methods to get "totalNofofFeaturesPassed","totalNofofFeaturesFailed","totalNofofFeaturesSkipped" and then maybe the same for scenarios

This is how my end report should look like for email notification:

<img width="340" alt="reportCustom" src="https://user-images.githubusercontent.com/66346463/89102824-55b71c00-d42a-11ea-8f31-acdbcf5ed6d4.png">

**Comment by rpii** [comment]
so if you look at the wdio/reporter interface it doesnt really provide those things: 
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-reporter
 you might ask on the webdriverio forum.

**Comment by sisirrana** [comment]
Thank you peter. I was able to generate the report using customreport +  cucumber html reporter.
