### ISSUE TITLE
TypeError: ReporterClass is not a constructor

### ISSUE THREAD

**Issue by senovsky** [webdriverio-community/wdio-html-reporter#4]
After upgrading to 0.7.0 or later, I get this error:

```
[0-0] 2019-04-23T21:47:06.387Z ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
     at BaseReporter.initReporter (C:\Users\senovsky\gitlab\weborder\fe\e2e\node_modules\@wdio\runner\build\reporter.js:193:14)
     at Array.map (<anonymous>)
     at new BaseReporter (C:\Users\senovsky\gitlab\weborder\fe\e2e\node_modules\@wdio\runner\build\reporter.js:34:39)
     at Runner.run (C:\Users\senovsky\gitlab\weborder\fe\e2e\node_modules\@wdio\runner\build\index.js:89:21)
     at process.on.m (C:\Users\senovsky\gitlab\weborder\fe\e2e\node_modules\@wdio\local-runner\build\run.js:37:20)
     at process.emit (events.js:194:15)
     at emit (internal/child_process.js:820:12)
     at process._tickCallback (internal/process/next_tick.js:63:19)
```

Maybe it's something I'm doing wrong, but simply downgrading to 0.6.6, without changing anything else, allows the reporter to work correctly. I'm not using the Master report functionality. Should more info be needed, I'll happily provide it.

**Comment by rpii** [comment]
Nikola,

could I see your reporter section of wdio.conf.js?  that is usually where the error is.  This is usually a something thing get compiled with babel type of issue.

**Comment by senovsky** [comment]
The reporter section is copied from your README, with only minor changes:
```
    reporters: ['spec',
        ['@rpii/wdio-html-reporter', {
            debug: false,
            outputDir: './reports/',
            filename: 'report.html',
            reportTitle: 'Test Report',
            showInBrowser: true
        }
        ]
    ],
```

Here's the whole file (extension should be .js)
[wdio.conf.txt](https://github.com/rpii/wdio-html-reporter/files/3112598/wdio.conf.txt)

**Comment by rpii** [comment]
It will work if you add this to the top of your file:
`import { ReportAggregator, HtmlReporter} from '@rpii/wdio-html-reporter';`

and then use
```
        [HtmlReporter, {
            debug: false,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'Test Report',
            showInBrowser:false,
            useOnAfterCommandForScreenshot:false
        }
        ],

```

**Comment by senovsky** [comment]
Good news: The report is being generated again :-)
Bad news: The screenshots are now missing :-(
No matter if I set the property `useOnAfterCommandForScreenshot` to true or false, the only thing I get is an empty folder `reportsscreenshots`.
Here's my typed config (extension should be .ts):
[wdio.conf.txt](https://github.com/rpii/wdio-html-reporter/files/3113938/wdio.conf.txt)
Line 232 is commented because it used to take a screenshot twice in JS and now in TS it complains that `Argument of type '"test:screenshot"' is not assignable to parameter of type 'Signals'.ts(2345)`

**Comment by rpii** [comment]
Well,  you wont see the screenshots unless the emitted signal gets to the reporter.  You do need the line that is commented out.f  The issue to me looks like a typescript issue,  because the first parameter to emit is a string with the event name.  To use the useOnAfterCommandForScreenshot  set it to true, and the following code in the reporter will execute everytime takeScreenshot is called:  

```
    //this is a hack to get around lack of onScreenshot event
    onAfterCommand(command) {
        if (this.options.useOnAfterCommandForScreenshot) {
            if (this.isScreenshotCommand(command) && command.result.value) {
                const timestamp = moment().format('YYYYMMDD-HHmmss.SSS');
                const filepath = path.join(this.options.outputDir, '/screenshots/', this.cid, timestamp, this.options.filename + '.png');
                fs.outputFileSync(filepath, Buffer.from(command.result.value, 'base64'));

                let test = this.getTest(this.testUid);
                test.events.push({type: 'screenshot', value: filepath});
            }
        }
    }
```

**Comment by senovsky** [comment]
So I tried using the `onAfterCommand` code, in both TS config and JS config.
In TS config, several properties do not exist on type `Config`:
```
2019-04-25T11:32:09.815Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: C:\Users\senovsky\gitlab\WebdriverIO_v5_TypeScript-master\wdio.conf.js: ⨯ Unable to compile TypeScript:
wdio.conf.ts(256,3): error TS2322: Type '{ runner: string; specs: string[]; maxInstances: number; capabilities: ({ browserName: string; maxInstances: number; } | { browserName: string; 'goog:chromeOptions': { args: string[]; }; maxInstances: number; })[]; ... 11 more ...; onAfterCommand(command: any): void; }' is not assignable to type 'Config'.
  Object literal may only specify known properties, but 'onAfterCommand' does not exist in type 'Config'. Did you mean to write 'afterCommand'?
wdio.conf.ts(257,14): error TS2339: Property 'options' does not exist on type 'Config'.
wdio.conf.ts(258,16): error TS2339: Property 'isScreenshotCommand' does not exist on type 'Config'.
wdio.conf.ts(259,27): error TS2304: Cannot find name 'moment'.
wdio.conf.ts(260,26): error TS2304: Cannot find name 'path'.
wdio.conf.ts(260,41): error TS2339: Property 'options' does not exist on type 'Config'.
wdio.conf.ts(260,82): error TS2339: Property 'cid' does not exist on type 'Config'.
wdio.conf.ts(260,103): error TS2339: Property 'options' does not exist on type 'Config'.
wdio.conf.ts(261,9): error TS2304: Cannot find name 'fs'.
wdio.conf.ts(263,27): error TS2339: Property 'getTest' does not exist on type 'Config'.
wdio.conf.ts(263,40): error TS2339: Property 'testUid' does not exist on type 'Config'.
```

In JS config, the `onAfterCommand` code works, but no screenshots are taken anyway.
Setting `useOnAfterCommandForScreenshot` to false and using the original `afterTest: function (test)` from README didn't help either.

**Comment by rpii** [comment]
So I am sorry if I confused the issue.  That code already exists in the reporter,  you turn it on with the boolean useOnAfterCommandForScreenshot.  You dont need it in your code.    What I do in my tests which use the reporter is extend the base page object and call the function takeScreenshot below to take a screen shot.  Then you can set the above boolean to false.

[base.page.js.txt](https://github.com/rpii/wdio-html-reporter/files/3117105/base.page.js.txt)

**Comment by senovsky** [comment]
Ah OK, now I get it :-D There's a hook in wdio.conf.js called `afterCommand` which confused me into thinking that I should put the `onAfterCommand` code there.
However, I switched back to JS config and regardless of whether I set `useOnAfterCommandForScreenshot` to false or true, or if I use the `afterTest: function` or not, there are still no screenshots taken. It isn't a pressing issue right now, I'll create a separate issue for it if necessary.
The ReporterClass problem has already been solved anyway. I would recommend updating the README with the new information. You can also include that if someone isn't using Babel, they need to import the reporter like this: `const HtmlReporter = require('@rpii/wdio-html-reporter').HtmlReporter;
`

**Comment by rpii** [comment]
I will update the documentation.  did you have success with screenshots using the page object function in my previous comment?  that should work just fine.

**Comment by senovsky** [comment]
I did not have success using the code from `base.page.js.txt`. I put it into wdio.conf.js, so that afterTest looks like this:
```
    afterTest: function (test) {
        const path = require('path');
        const moment = require('moment');
        const fs = require("fs-extra");

        const timestamp = moment().format('YYYYMMDD-HHmmss.SSS');
        fs.ensureDirSync('reports/screenshots/');
        const filepath = path.join('reports/screenshots/', timestamp + '.png');
        this.browser.saveScreenshot(filepath);
        this.logMessage(message);
        process.emit('test:screenshot', filepath);
        return this;
    },
```
Should I have put it somewhere else?
Btw just for reference, I tried v0.6.6 again and the screenshots work just fine in that version.

**Comment by rpii** [comment]
If you use that base.page as a base class for all of your page objects,  the take screenshot is available everywhere.    The top of  my page objects:
```
import BasePage from './base.page';
import {expect} from 'chai';

class LoginPage extends BasePage { ....
```

**Comment by AbhilashRV** [comment]
@rpii , Still "ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor" at BaseReporter.initReporter. Default logFile creation method is not handled properly and that could be creating this problem

**Comment by rpii** [comment]
We changed the log file creation some time back.  are you using the latest version?

**Comment by AbhilashRV** [comment]
@rpii  7.6.0 version. Do I need to add any code at hooks ?

**Comment by AbhilashRV** [comment]
@rpii   Could you please share the config.js file ?

**Comment by MahaJampala** [comment]
I am getting this error..
ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor.
Can you please provide the solution
