### ISSUE TITLE
Screenshots not coming for url navigation

### ISSUE THREAD

**Issue by qburst-hari** [webdriverio-community/wdio-html-reporter#41]
I have made the option "useOnAfterCommandForScreenshot" to true. but still for url navigation or opening html pages, screenshots are not getting attached to report. I am using webdriverIO6 with cucumber

**Comment by rpii** [comment]
you need to add the sample code shown in

afterTest: function (test) {
    const path = require('path');
    const moment = require('moment');

    // if test passed, ignore, else take and save screenshot.
    if (test.passed) {
        return;
    }
    const timestamp = moment().format('YYYYMMDD-HHmmss.SSS');
    const filepath = path.join('reports/html-reports/screenshots/',
timestamp + '.png');
    browser.saveScreenshot(filepath);
    process.emit('test:screenshot', filepath);
},


if that is not working maybe cucumber is not firing this event.

**Comment by rpii** [comment]
no response
