### ISSUE TITLE
Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio--reporter" or a function/class.

### ISSUE THREAD

**Issue by nam81285** [webdriverio-community/wdio-html-reporter#47]
get an error when i use HtmlReporter in my webdriverio config.

Here are the versions:

  "@rpii/wdio-html-reporter": "^6.2.0",
    "@wdio/allure-reporter": "^6.11.0",
    "@wdio/cli": "^6.12.1",
    "@wdio/cucumber-framework": "^6.11.1",
    "@wdio/dot-reporter": "^6.11.0",
    "@wdio/local-runner": "^6.12.1",
    "@wdio/selenium-standalone-service": "^6.12.1",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",
    "webdriverio": "6.12.1"

// ============
    // Capabilities
    // ============
    //Defined a headless browser only
    capabilities: [{
        maxInstances: 0,
        // //
        browserName: 'chrome',
        "goog:chromeOptions": {
            headless: true
        },
        //binary: `./tools/chrome.exe`,
        acceptInsecureCerts: true
    }],

//Reporter config in wdio config file:
let {ReportAggregator, HtmlReporter} = require('@rpii/wdio-html-reporter');
const log4j = require("log4js");
let localConfig = {
    reporters: ["spec",
    [HtmlReporter, {
        debug: true,
        outputDir: './tests/reports/output/html/',
        filename: 'report.html',
        reportTitle: 'Test Report Title',
        showInBrowser: true,
        useOnAfterCommandForScreenshot: false,
       LOG: log4j.getLogger("default")
    }
    ]
],
};
exports.config = override(localConfig, instanceConfig, true);

//Hooks:

    onPrepare: function (config, capabilities) {
        let reportAggregator = new ReportAggregator({
            outputDir: './tests/reports/output/html/',
            filename: 'master-report.html',
            reportTitle: 'Master Report',
            browserName : capabilities.browserName,
            collapseTests: true,
            // to use the template override option, can point to your own file in the test project:
            // templateFilename: path.resolve(__dirname, '../template/wdio-html-reporter-alt-template.hbs')
        });
        reportAggregator.clean() ;

        global.reportAggregator = reportAggregator;
    },

    onComplete: function(exitCode, config, capabilities, results) {
        (async () => {
            await global.reportAggregator.createReport();
        })();
    },

Errors are:

[0-0] 2021-01-22T10:48:27.990Z ERROR @wdio/runner: Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter.html)
    at Object.validateConfig (./node_modules/@wdio/config/build/utils.js:118:27)

[0-1] 2021-01-22T10:48:28.011Z ERROR @wdio/local-runner: Failed launching test session: Error: Invalid reporters config
    at BaseReporter.initReporter (./node_modules/@wdio/runner/build/reporter.js:103:15)

**Comment by rpii** [comment]
I dont see this section of the config file:
    reporters: [
        'spec',
        // ['junit', {
        //     outputDir: './reports/junit-reports/',
        //     outputFileFormat: function(opts) { // optional
        //         return `results-${opts.cid}.${opts.capabilities}.xml`
        //     }
        // }
        // ],
        [HtmlReporter, {
            debug: false,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'Web Test Report',
            showInBrowser: false,
            LOG: logger,
            useOnAfterCommandForScreenshot: false

        }
        ]
    ],

**Comment by nam81285** [comment]
let localConfig = {
reporters: ["spec",
[HtmlReporter, {
debug: true,
outputDir: './tests/reports/output/html/',
filename: 'report.html',
reportTitle: 'Test Report Title',
showInBrowser: true,
useOnAfterCommandForScreenshot: false,
LOG: log4j.getLogger("default")
}
]
],
};
exports.config = override(localConfig, instanceConfig, true);

I have this defined..

**Comment by nam81285** [comment]
Hi Rich,

I have the below defined in config file

> //Reporter config in wdio config file:
> let {ReportAggregator, HtmlReporter} =
require('@rpii/wdio-html-reporter');
> const log4j = require("log4js");
> let localConfig = {
> reporters: ["spec",
> [HtmlReporter, {
> debug: true,
> outputDir: './tests/reports/output/html/',
> filename: 'report.html',
> reportTitle: 'Test Report Title',
> showInBrowser: true,
> useOnAfterCommandForScreenshot: false,
> LOG: log4j.getLogger("default")
> }
> ]
> ],
> };
> exports.config = override(localConfig, instanceConfig, true);

Regards,
Namita

**Comment by rpii** [comment]
Still seems like the structure is not correct:
 exports.config = override(localConfig, instanceConfig, true);
look at that config object in the debugger and make sure that reporters is
a property of that object.

Rich

**Comment by nam81285** [comment]
I tried the below method as well:

**My Complete config file:-
---------------------------------**
let {ReportAggregator, HtmlReporter} = require('@rpii/wdio-html-reporter');
process.env.ff = (argv.ff) ? argv.ff : process.env.ff;
let featureFilePath = process.env.ff === "undefined" ? `./tests/features/featureFiles/**/*.feature` : `./tests/features/featureFiles/**/${argv.ff}.feature`;
exports.config = {
    runner: "local",
    // Patterns to exclude.
    specs: [
        featureFilePath
    ],
    // ============
    // Capabilities
    // ============
    //Defined a headless browser only
    capabilities: [{
        maxInstances: 0,
        // //
        browserName: 'chrome',
        "goog:chromeOptions": {
            headless: true
        },
        acceptInsecureCerts: true,
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    logLevel: "error",
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    // Default request retries count
    connectionRetryCount: 3,
    // Test runner services
    framework: "cucumber",
    reporters: ['spec',
        [HtmlReporter, {
            debug: false,
            outputDir: './tests/reports/output/html/',
            filename: 'report.html',
            reportTitle: 'Web Test Report',
            showInBrowser: false,
            useOnAfterCommandForScreenshot: false
        }]
    ],
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ["./tests/features/step_definitions/**/*.steps.js"],
        strict: true,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: "",
        // <number> timeout for step definitions
        timeout: 60000,
    },
};
console.log ("exportsConfig :- ",exports.config)

**The Above Console.log is giving below result for the reporter part:-
---------------------------------------------------------------------**
exportsConfig :-  {
  runner: 'local',
  specs: [ './tests/features/featureFiles/**/pep-post-passingHeader.feature' ],
  capabilities: [
    {
      maxInstances: 0,
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      acceptInsecureCerts: true
    }
  ],
  logLevel: 'error',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  framework: 'cucumber',

  **_reporters: [ 'spec', [ [class HtmlReporter extends WDIOReporter], [Object] ] ],_**

  cucumberOpts: {
    require: [ './tests/features/step_definitions/**/*.steps.js' ],
    strict: true,
    tagExpression: '',
    timeout: 60000
  },
}

**Error message is still the same:-**

[0-0] 2021-01-25T17:35:44.554Z ERROR @wdio/runner: Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter.html)
    at Object.validateConfig (/node_modules/@wdio/config/build/utils.js:118:27)

[0-0] 2021-01-25T17:35:44.567Z ERROR @wdio/local-runner: Failed launching test session: Error: Invalid reporters config
    at BaseReporter.initReporter (/node_modules/@wdio/runner/build/reporter.js:103:15)

**Comment by rpii** [comment]
It looks good.  is there a chance its a javascript execution issue?  are
you running this through babel?

Rich

**Comment by nam81285** [comment]
Hi Rich,

I am not using any external compiler. I mean nothing like babel or
typescript. Is it mandatory to use anyone of these?

If its mandatory can u help to configure it?

Also to let u know I use gulp to execute my script.

Can it be a version issue? I mean I have all the latest npm package
versions as per wdio v 6.2

As the error throwing from the below :

   - @wdio/runner
   <https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-runner>


   - @wdio/config
   <https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config>
-
   A helper utility to parse and validate WebdriverIO options


I really want to resolve it. I like the report a lot as it can also be
converter to pdf.


Regards,
Namita

**Comment by rpii** [comment]
does it work if you simplify the reports section?  just put in spec?

Rich

**Comment by nam81285** [comment]
Hi Rich,

I have tried other reports like timeline, spec, dot, allure repot, json and
cucumber-json (with multiple- cucumber-reporter for html). All of these
works together and individually fine for me.

But HTML reporter looks simple and it has pdf converter so I want this to
work.

Thanks,
Namita

**Comment by rpii** [comment]
So I am not sure what is failing.  it works for most folks.  can you send
me your config file?

Rich

**Comment by nam81285** [comment]
Hi Rich,

Below is my config file goes by name local.conf.js. I am calling config
file in my gulp task.
********************************************************
let {ReportAggregator, HtmlReporter} = require('@rpii/wdio-html-reporter');
process.env.ff = (argv.ff) ? argv.ff : process.env.ff;
let featureFilePath = process.env.ff === "undefined" ?
./tests/features/featureFiles/**/*.feature :
./tests/features/featureFiles/**/${argv.ff}.feature;
exports.config = {
runner: "local",
// Patterns to exclude.
> specs: [
> featureFilePath
> ],
> // ============
> // Capabilities
> // ============
> //Defined a headless browser only
> capabilities: [{
> maxInstances: 0,
> // //
> browserName: 'chrome',
> "goog:chromeOptions": {
> headless: true
> },
> acceptInsecureCerts: true,
> }],
> //
> // ===================
> // Test Configurations
> // ===================
> logLevel: "error",
> waitforTimeout: 10000,
> connectionRetryTimeout: 120000,
> // Default request retries count
> connectionRetryCount: 3,
> // Test runner services
> framework: "cucumber",
> reporters: ['spec',
> [HtmlReporter, {
> debug: false,

> outputDir: './tests/reports/output/html/',
> filename: 'report.html',
> reportTitle: 'Web Test Report',
> showInBrowser: false,
> useOnAfterCommandForScreenshot: false
> }]
> ],
> // If you are using Cucumber you need to specify the location of your step
> definitions.
> cucumberOpts: {
> // <string[]> (file/dir) require files before executing features
> require: ["./tests/features/step_definitions/**/*.steps.js"],
> strict: true,
> // (expression) only execute the features or scenarios with tags matching
> the expression
> tagExpression: "",
> // timeout for step definitions
> timeout: 60000,
> },
> };
******************************************************************************
Do u have any sample project with wdio v6+Cucumber v6+ HTML Reporter for me
to refer?

Regards,
Namita

**Comment by nam81285** [comment]
Hi @rpii,
Do u think babel or typescript is mandatory to generate this report? Also do I need any mandatory services or Packages defined in my config and package.json respectively?

**Comment by rpii** [comment]
I have a cucumber sample, but I dont want it to be public.  I could send it
to you as a zip

Rich

**Comment by nam81285** [comment]
Thanks @rpii (Rich). I figured out the issue I guess. Need you help to understand though.
does this report work with gulp tasks?
I mean in my framework i use gulp command to execute the cases.. below is a sample:-

gulp.task('run-api', () => {
    return gulp.src('tests/conf/wdio.conf.js').pipe(webdriver({
        wdioBin: path.join(__dirname, 'node_modules', '.bin', cmd)
    }));
});

When I run the wdio.conf.js directly without gulp task (command- npx wdio ./tests/conf/wdio.conf.js) the report is getting generated but when i use gulp command (gulp run-api <featurefile name>) its giving the reporter error.

Could you help me with resolving this?

**Comment by rpii** [comment]
you have to use wdio  to run it, as in the last example.  it sets up the
environment

**Comment by nam81285** [comment]
Thanks I also figured that out.

So I cannot use this report. 😒

Thanks for your help and time.

Regards,
Namita rath

**Comment by rpii** [comment]
obe
