### ISSUE TITLE
QQ: Has jQuery been used only in UI?

### ISSUE THREAD

**Issue by Askarov5** [webdriverio-community/wdio-html-reporter#50]
I see some jQuery code under the html template. And I was wondering if you use it only in UI? If it's only small part of the UI Why don't you get rid off jQuery completely in project level by using vanillaJS

**Comment by rpii** [comment]
Please feel free to try that out in a branch.  I am not actively developing
this at this moment.

**Comment by Askarov5** [comment]
Are you going to upgrade the base and make it compatible with Wdio Version 7 ?

**Comment by rpii** [comment]
I have not yet tested with v7 to see if there are incompatibilities.  It
will need to get upgraded if it no longer works.
