### ISSUE TITLE
Unable to see browser names in the master-report.html

### ISSUE THREAD

**Issue by Askarov5** [webdriverio-community/wdio-html-reporter#57]
Hi,
I 'm not able see the browser name in the report html file. Could you please show(give an example) how to set it correctly?
![Screen Shot 2021-05-19 at 11 27 06 PM](https://user-images.githubusercontent.com/13361800/119024372-9b68b500-b968-11eb-9ada-edcc8fd04dbd.png)

**Comment by rpii** [comment]
sample from chrome config file:
let baseConfig = require('./base.config') ;
exports.config = Object.assign({}, baseConfig.config, {
    path: '/',
    capabilities: [
        {
            // Set maxInstances to 1 if screen recordings are enabled:
            // maxInstances: 1,
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: [process.env.CHROME_ARGS]
            }
        }
    ],
    port: 9515, // default for ChromeDriver
    services: ['chromedriver'],
    chromeDriverLogs: './logs'
});

**Comment by rpii** [comment]
and in base.config:
    onPrepare: function (config, capabilities) {

        let reportAggregator = new ReportAggregator({
            outputDir: './reports/html-reports/',
            filename: 'master-report.html',
            reportTitle: 'Master Report',
            LOG: logger,
            showInBrowser: true,
            collapseTests: true,
            browserName : capabilities.browserName,
        });
        reportAggregator.clean() ;

        global.reportAggregator = reportAggregator;
    },

**Comment by rpii** [comment]
Added an example

**Comment by rpii** [comment]
to the readme.md file in your branch
