### ISSUE TITLE
electron-to-chromium, browserslist in yarn.lock

### ISSUE THREAD

**Issue by z41** [webdriverio-community/wdio-html-reporter#6]
Hello
Not sure if it's an issue or not, but 2 these packages (electron-to-chromium, browserslist) are present in yarn.lock for the reporter and are downloaded when installing a reporter. 
Electron-to-chromium in its turn requires Electron package which is a big one, that's why I noticed it.

Another thing is yarn-error.log file which as I understand is better to be removed from git.

**Comment by rpii** [comment]
Thats being pulled in by babel.  Not sure what I could do about that

**Comment by msyrus** [comment]
@z41 don't worry, they are required by `@babel/preset-env` which is a devDependency, so they will not be pulled in your project other than you want to develop/build this package by your own.

I think this issue can be closed.

**Comment by rpii** [comment]
closing...
