### ISSUE TITLE
Default Template does not render errors

### ISSUE THREAD

**Issue by tobias38** [webdriverio-community/wdio-html-reporter#62]
Hi,

I have an issue with version "7.7.11" of "wdio-html-nice-reporter" in combination with wdio version "7.7.4":

If a test suite fails the generated html report renders an empty "Assertion" text. The root cause is that it uses `event.message` as source but the actual content is in `event.value.message`. Same is true for the stack: The error stack is in `event.value.stack`.

https://github.com/rpii/wdio-html-reporter/blob/88fe43943824b4702a93a30e24492fd9c1d4ec3d/templates/wdio-html-reporter-template.hbs#L348

Can you please have a look at that?

Regards,
Tobias

**Comment by rpii** [comment]
yes I will have a look

**Comment by rpii** [comment]
tobias,

so the new version of webdriverio changed the event structure causing the
assertion to fail.  I have published a new version for 7.7.4 or higher.
There may be more issues but will have to do more testing.  the test cases
are static so they can not anticipate changes to objects.

Rich

**Comment by tobias38** [comment]
Thanks very much for this fast fix Rich. I can confirm that the errors are now getting rendered correctly with version 7.7.12 of wdio-html-nice-reporter
