### ISSUE TITLE
Capability to add video in HTML reporter

### ISSUE THREAD

**Issue by arun04arun95** [webdriverio-community/wdio-html-reporter#77]
### New Feature
**wdio-video-reporter** library will help to generate video for the test. Need capability to attach and play the video from the master HTML test report.

**Comment by rpii** [comment]
I will investigate this sometime this week.

Rich

**Comment by rpii** [comment]
Ok this was easier than it looked.  nice-html-reporter is updated,  but it requires a patch to wdio-video-reporter.  see version 7.9.1 of nice-html-reporter.  You can just patch your local copy of wdio-video-reporter after installing until the pull request is accepted .  see the repo in the changelog.   let me know if it works for you.

**Comment by nair-sumesh** [comment]
Video is being recorded and saved to the location. However, the generated HTML does not link it correctly.
It adds the path _suite-0-1/0-0/_ in the url. Config used exactly same as described [here](https://www.npmjs.com/package/wdio-video-reporter) 

**Expected Link**
 file:///C:/Users/xxxxxxxxxxxxxx/spec/reports/html-reports/bootstrap--login--CHROME--01-27-2022--12-16-27-980.mp4

**Actual generated Link**
file:///C:/Users/xxxxxxxxxxxxxx//spec/reports/html-reports/**suite-0-1/0-0**/bootstrap--login--CHROME--01-27-2022--12-16-27-980.mp4

**Comment by rpii** [comment]
Are you using the aggregated report?

**Comment by rpii** [comment]
Per the readme you likely need:


            outputDir: 'reports/html-reports/screenshots',

in the video reporter configuration

**Comment by gromanas** [comment]
Hello! I had the same issue as @arun04arun95. After I followed your instruction @rpii and indeed with 7.9.1 version of html-nice-reporter, I am now able to see the attached video player. I don't know if I should comment this here, but now I am facing an issue with .mp4. Actually, I am just getting in the outputDir a folder `rawSeleniumVideoGrabs` that includes only the images that have been taken during the test execution and no video included, although I am getting in logs:
```
 "Video" Reporter:

Generated:[]



Video reporter Done!

Generated:[
  "/Users/user/projects/game/reports/html-reports/screenshots/Manually-add-numbers-and-win-Jackpot-Tier--CHROME--02-09-2022--19-56-19-718.mp4"
]



Video reporter Done!

Generated:[]



Video reporter Done!
```

Thank you in advance!

**Comment by arun04arun95** [comment]
Hey @rpii,

This feature enhancement is tested and working fine with my project. thanks for picking. Closing the ticket

_wdio-video-reporter library will help to generate video for the test. Need capability to attach and play the video from the master HTML test report._
