### ISSUE TITLE
Support for custom html template

### ISSUE THREAD

**Issue by msyrus** [webdriverio-community/wdio-html-reporter#9]

**Comment by rpii** [comment]
Could you indicate what you are looking for? perhaps a sample template for the report output?

**Comment by msyrus** [comment]
I would like to request an option to invoke custom template functions and use developer's own html template where a default option could be [this](../blob/master/src/wdio-html-reporter-template.hbs).

**Comment by msyrus** [comment]
I would like to send an PR if you agree on this.

**Comment by rpii** [comment]
You can send a PR, but I mocked up something that you can easily play with.  the 7.8 version will accept a templateFilename option that points to your template.  Or you can directly edit src/wdio-html-reporter-alt-template.hbs.  

Please let me know what alternate css you might come up with.  If it looks great we can include it as an option.

**Comment by ghost** [comment]
Hey, does the last 0.7.8 release stopped generating master report? Should I change configuration?

**Comment by rpii** [comment]
yep looks like I broke it.  Ill get it fixed
Use 0.7.7 for now
